name: Autofix

on:
  workflow_call:
    inputs:
      ref:
        description: 'The Git ref (branch, tag, or SHA) to checkout'
        required: true
        type: string

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  rector-check:
    runs-on: ubuntu-latest
    name: Run Rector Checks

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader --no-scripts

      - name: Run Rector
        run: composer rector -- --dry-run --ansi

      - name: Check for changes
        run: |
          if ! git diff --exit-code; then
            echo "‚ùå Rector found pending changes! Please run 'composer rector' locally and commit the fixes."
            exit 1
          fi
