name: Testing

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader --no-scripts

      - name: Run Tests
        run: composer test

      - name: Generate coverage report
        uses: mridang/action-test-reporter@v3
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: 'build/coverage/clover.xml'

      - name: Upload Results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: always()
        with:
          name: test-results
          path: build/reports/**/*.xml

      - name: Generate Report
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        uses: dorny/test-reporter@b082adf0eced0765477756c2a610396589b8c637 # v2.5.0
        with:
          name: Tests
          reporter: java-junit
          path: build/reports/**/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
